/*
 * File: app/view/main/Menu.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Instinct.view.main.Menu', {
    extend: 'Ext.Panel',
    alias: 'widget.mainMenu',

    requires: [
        'Ext.TitleBar',
        'Ext.Img',
        'Ext.Button'
    ],

    config: {
        cls: 'mainMenuCss',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'titlebar',
                cls: 'instinctTitle',
                docked: 'top',
                title: 'Team Instinct App'
            },
            {
                xtype: 'container',
                style: 'border-top:1px solid #0e0e0e;border-bottom:1px solid #0e0e0e;',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'container',
                        cls: 'menuButtonHolder',
                        itemId: 'profileHolder',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'image',
                                cls: 'menuIcon',
                                width: 50,
                                src: 'resources/images/icons/profile.png'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                cls: 'menuButton',
                                itemId: 'profile',
                                text: 'Profile'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        cls: 'menuButtonHolder',
                        itemId: 'mapHolder',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'image',
                                cls: 'menuIcon',
                                width: 50,
                                src: 'resources/images/icons/map.png'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                cls: 'menuButton',
                                itemId: 'Map',
                                text: 'Map'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        cls: 'menuButtonHolder',
                        itemId: 'inventoryHolder',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'image',
                                cls: 'menuIcon',
                                width: 50,
                                src: 'resources/images/icons/inventory.png'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                cls: 'menuButton',
                                itemId: 'inventory',
                                text: 'Inventory'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        cls: 'menuButtonHolder',
                        itemId: 'friendsHolder',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'image',
                                cls: 'menuIcon',
                                width: 50,
                                src: 'resources/images/icons/friends.png'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                cls: 'menuButton',
                                itemId: 'friends',
                                text: 'Friends'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        cls: 'menuButtonHolder',
                        itemId: 'chatHolder',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'image',
                                cls: 'menuIcon',
                                width: 50,
                                src: 'resources/images/icons/chat.png'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                cls: 'menuButton',
                                itemId: 'chat',
                                text: 'Chat'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        cls: 'menuButtonHolder',
                        itemId: 'messagesHolder',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'image',
                                cls: 'menuIcon',
                                width: 50,
                                src: 'resources/images/icons/messages.png'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                cls: 'menuButton',
                                itemId: 'messages',
                                text: 'Messages'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        cls: 'menuButtonHolder',
                        itemId: 'settingsHolder',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'image',
                                cls: 'menuIcon',
                                width: 50,
                                src: 'resources/images/icons/settings.png'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                cls: 'menuButton',
                                itemId: 'settings',
                                text: 'Settings'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        cls: 'menuButtonHolder',
                        itemId: 'LogoutHolder',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'image',
                                cls: 'menuIcon',
                                width: 50,
                                src: 'resources/images/icons/logout.png'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                cls: 'menuButton',
                                itemId: 'logout',
                                text: 'Logout'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});