/*
 * File: app/view/user/Login.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Instinct.view.user.Login', {
    extend: 'Ext.Panel',
    alias: 'widget.instinctMain',

    requires: [
        'Ext.Img',
        'Ext.Container',
        'Ext.field.Password',
        'Ext.Button',
        'Ext.TitleBar'
    ],

    config: {
        style: 'background-color: #000;',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'image',
                height: 150,
                style: 'background-size:contain;',
                src: 'resources/images/login.jpg'
            },
            {
                xtype: 'container',
                itemId: 'loginPanel',
                items: [
                    {
                        xtype: 'container',
                        cls: 'loginLabel',
                        html: 'username'
                    },
                    {
                        xtype: 'textfield',
                        cls: 'inputLogin',
                        clearIcon: false,
                        name: 'username',
                        placeHolder: '<username>'
                    },
                    {
                        xtype: 'container',
                        cls: 'loginLabel',
                        html: 'password'
                    },
                    {
                        xtype: 'passwordfield',
                        cls: 'inputLogin',
                        clearIcon: false,
                        name: 'password',
                        placeHolder: '**********'
                    },
                    {
                        xtype: 'button',
                        cls: 'loginButton',
                        itemId: 'loginButton',
                        margin: 20,
                        padding: 8,
                        text: 'LOGIN'
                    },
                    {
                        xtype: 'button',
                        cls: 'loginButton',
                        itemId: 'showRegisterButton',
                        margin: 20,
                        padding: 8,
                        text: 'REGISTER'
                    }
                ]
            }
        ]
    }

});