/*
 * File: app/view/user/Settings.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Instinct.view.user.Settings', {
    extend: 'Ext.Panel',
    alias: 'widget.settings',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.Img'
    ],

    config: {
        cls: 'settingsController',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'titlebar',
                baseCls: 'instinctTitleBack',
                docked: 'top',
                items: {
                    xtype: 'button',
                    cls: 'backButton',
                    itemId: 'backToMenu',
                    html: 'Back'
                },
                title: 'Settings'
            },
            {
                xtype: 'container',
                cls: 'settingsPanel',
                height: '100%',
                itemId: 'settingsPanel',
                maxHeight: '100%',
                minHeight: '100%',
                items: [
                    {
                        xtype: 'button',
                        cls: 'saveButton',
                        docked: 'bottom',
                        itemId: 'saveButton',
                        margin: 20,
                        padding: 8,
                        text: 'SAVE'
                    }
                ]
            }
        ]
    }

});