/*
 * File: app/controller/nativeFunctions/devicePlugin.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Instinct.controller.nativeFunctions.devicePlugin', {
    extend: 'Ext.app.Controller',

    config: {
    },

    phoneData: function() {
        data = {
            "uuid"			: device.uuid,
            "platform"		: device.platform,
            "model"			: device.model,
            "manufacturer"	: device.manufacturer
        };
        return data;
    }

});