/*
 * File: app/controller/server/checkPlayerData.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Instinct.controller.server.checkPlayerData', {
    extend: 'Ext.app.Controller',

    config: {
    },

    checkToken: function(callbackFn) {
        var userId		= settings.get('userId');
        var userToken	= settings.get('userToken');
        if(userId === false || userToken === false){
            callbackFn(false);
        }else{
            var successCallback = function(resp, ops) {
                if(resp.status === 200){
                    var responseData = Ext.JSON.decode(resp.responseText);
                    if(responseData.errorHandle == "alert"){
                        if(responseData.errorText !== ""){
                            Ext.Msg.alert(false, responseData.errorText);
                        }
                        if(responseData.successText !== ""){
                            Ext.Msg.alert(false, responseData.successText);
                        }
                    }
                    if(responseData.success === true){
                        callbackFn(true);
                    }else{

                        callbackFn(false);
                    }
                }else{
                    Ext.Msg.alert(false,"Login server down, Please try again later!");
                    callbackFn(false);
                }
            };
            var failureCallback = function(resp, ops) {
                callbackFn(false);
            };

            Ext.Ajax.request({
                url: "http://iriks-it.nl/PokemonGo/Instinct/modules/authentication/checkToken.php",
                disableCaching: false,
                headers: {
                    "Content-Type": "application/json"
                },
                method: 'POST',
                jsonData: {
                    "userid": userId,
                    "token"	: userToken,
                },
                success: successCallback,
                failure: failureCallback
            });
        }
    }

});