/*
 * File: app/controller/user/Login.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Instinct.controller.user.Login', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            Main: 'Main'
        },

        control: {
            "instinctMain button#showRegisterButton": {
                tap: 'showRegister'
            },
            "instinctMain button#loginButton": {
                tap: 'login'
            }
        }
    },

    showRegister: function(button, e, eOpts) {
        viewAlias = "userRegister";
        nav = button.up("navigationview");
        pageToPush = Ext.widget(viewAlias);
        nav.push(pageToPush);

    },

    login: function(button, e, eOpts) {
        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            message: 'Loading...'
        });

        var username = button.up("instinctMain").down('textfield[name=username]').getValue();
        var password = button.up("instinctMain").down('textfield[name=password]').getValue();
        var userData = [];

        var successCallback = function(resp, ops) {
            if(resp.status === 200){
                var responseData 	= Ext.JSON.decode(resp.responseText);
                var userResult		= responseData.user;
                if(responseData.success === true){
                    settings.set('userId', userResult.id);
                    settings.set('userToken', userResult.token);
                    Ext.Viewport.unmask();

                    if(userResult.locked === 1){
                        Ext.Msg.alert(false, userResult.lockedText);
                    }else{
                        if(userResult.complete === 0){
                            Ext.Msg.alert(false, userResult.completeText);
                            viewAlias 	= "userUploadProfile";
                            nav 		= button.up("navigationview");
                            pageToPush 	= Ext.widget(viewAlias);
                            nav.push(pageToPush);
                        }else{
                            if(userResult.complete === 1 && userResult.verified === 0){
                                Ext.Msg.alert(false, userResult.holdText);
                            }else{
                                viewAlias 	= "mainMenu";
                                nav 		= button.up("navigationview");
                                pageToPush 	= Ext.widget(viewAlias);
                                nav.push(pageToPush);
                            }
                        }
                    }
                }else{
                    Ext.Viewport.unmask();
                    Ext.Msg.alert(false, responseData.error);
                }
            }else{
                Ext.Viewport.unmask();
                Ext.Msg.alert(false, "Login server down, Please try again later!");
            }
        };
        var failureCallback = function(resp, ops) {
            Ext.Viewport.unmask();
            Ext.Msg.alert(false, "Login Failure");
        };

        if(username !== "" && password !== ""){
            Ext.Ajax.request({
                url: "http://iriks-it.nl/PokemonGo/Instinct/modules/authentication/login.php",
                disableCaching: false,
                headers: {
                    "Content-Type": "application/json"
                },
                method: 'POST',
                jsonData: {
                    "username": username,
                    "password": password,
                },
                success: successCallback,
                failure: failureCallback
            });
        }else{
            Ext.Viewport.unmask();
            Ext.Msg.alert(false, "Please fill in the form");
        }
    }

});