/*
 * File: app/controller/main/Menu.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Instinct.controller.main.Menu', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "mainMenu button": {
                tap: 'onMenuButtonTap'
            }
        }
    },

    onMenuButtonTap: function(button, e, eOpts) {
        navigationview = button.up('navigationview');
        viewport = button.up("mainViewport");

        if(button.getItemId() !== "logout"){
            //pageToOpen = Ext.widget(button.getItemId());
            Ext.Msg.alert(false, 'This option is not yet available in this version');
            //navigationview.push(pageToOpen);
        } else {
            Ext.Msg.confirm(false,"Are you sure you want to log out?",checkButton);
            function checkButton(btn) {
                if(btn == "yes") {
                    var controller = Instinct.app.getController("client.settings");
                    controller.removeAll(function(serverVersion){
                        nav = button.up('navigationview');
                        nav.pop();
                    });
                }
            }
        }
    }

});